# Generated by Django 3.0.6 on 2020-05-25 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_idArticle', models.AutoField(primary_key=True, serialize=False)),
                ('_nom', models.CharField(max_length=50)),
                ('_type', models.CharField(max_length=100)),
                ('_quantite', models.FloatField()),
                ('_image', models.ImageField(upload_to='')),
                ('_prix', models.PositiveSmallIntegerField()),
                ('_description', models.TextField()),
                ('_diponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nomIngred', models.CharField(max_length=100)),
                ('_prixIngred', models.FloatField()),
                ('_quantiteIngred', models.FloatField()),
                ('_quantiteStock', models.FloatField()),
                ('_typeIngred', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_password', models.CharField(max_length=100)),
                ('_login', models.CharField(max_length=100, unique=True)),
                ('_nom', models.CharField(max_length=100)),
                ('_prenom', models.CharField(max_length=100)),
                ('_dateNaissance', models.DateField()),
                ('_dateInscription', models.DateField(default=django.utils.timezone.now)),
                ('_nationalite', models.CharField(max_length=100)),
                ('_email', models.EmailField(max_length=255)),
                ('_profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sprint1.Utilisateur')),
                ('_tel', models.CharField(max_length=20, null=True)),
            ],
            bases=('Sprint1.utilisateur',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sprint1.Utilisateur')),
                ('_tel', models.CharField(max_length=20, null=True)),
            ],
            bases=('Sprint1.utilisateur',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sprint1.Utilisateur')),
                ('_etablissement', models.CharField(max_length=20)),
            ],
            bases=('Sprint1.utilisateur',),
        ),
        migrations.CreateModel(
            name='Desserte',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sprint1.Utilisateur')),
                ('_tel', models.CharField(max_length=20)),
            ],
            bases=('Sprint1.utilisateur',),
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_quantite', models.FloatField()),
                ('_idArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint1.Ingredient')),
                ('_idIngrediant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint1.Article')),
            ],
        ),
    ]
