# Generated by Django 3.0.5 on 2020-06-10 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sprint1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueil',
            old_name='_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='_etablissement',
            new_name='etablissement',
        ),
        migrations.RenameField(
            model_name='desserte',
            old_name='_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='_nationalite',
            new_name='nationalite',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='_nom',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_dateInscription',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_dateNaissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='_profession',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
