# Generated by Django 3.0.5 on 2020-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0002_auto_20200528_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='_quantiteIngred',
        ),
    ]
