# Generated by Django 3.0.5 on 2020-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0006_remove_admin_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
