# Generated by Django 3.0.5 on 2020-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0007_admin_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='_etablissement',
            new_name='etablissement',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(null=True),
        ),
    ]
