# Generated by Django 3.0.5 on 2020-06-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0009_auto_20200610_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desserte',
            old_name='_tel',
            new_name='tel',
        ),
    ]
