# Generated by Django 3.0.5 on 2020-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='_nomIngred',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
