# Generated by Django 3.0.5 on 2020-06-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0005_auto_20200605_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='tel',
        ),
    ]
