# Generated by Django 3.0.5 on 2020-06-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint1', '0008_auto_20200610_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueil',
            old_name='_tel',
            new_name='tel',
        ),
    ]
